/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pagosEmpresa;

import javax.swing.JOptionPane;

public class App {

    public static void main(String[] args) {
        
    }

    public Object getGreeting() {
        return null;
    }
}
